In [1]:
import pandas as pd

In [2]:
import numpy as np

In [7]:
a = np.random.randint(0, 10, 24).reshape(4, 6)
df = pd.DataFrame(a, index = list("가나다라"), columns = list("ABCDEF"))

In [8]:
df

   A  B  C  D  E  F
가  5  6  5  5  6  4
나  3  8  8  1  6  9
다  6  9  2  5  6  4
라  1  6  0  1  4  9

In [9]:
df

   A  B  C  D  E  F
가  5  6  5  5  6  4
나  3  8  8  1  6  9
다  6  9  2  5  6  4
라  1  6  0  1  4  9

In [12]:
df[0:1]

   A  B  C  D  E  F
가  5  6  5  5  6  4

In [13]:
df["A"]

가    5
나    3
다    6
라    1
Name: A, dtype: int64

In [14]:
df.loc["가":"다", "A" : "E"]

   A  B  C  D  E
가  5  6  5  5  6
나  3  8  8  1  6
다  6  9  2  5  6

In [16]:
df.loc["가":"다", ["A", "E", "E"]]

   A  E  E
가  5  6  6
나  3  6  6
다  6  6  6

In [19]:
df.loc[["가"]]

   A  B  C  D  E  F
가  5  6  5  5  6  4